// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 02-ServerStreaming/proto/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93e2bcf4a3ea62, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetManyRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetManyRequest) Reset()         { *m = GreetManyRequest{} }
func (m *GreetManyRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyRequest) ProtoMessage()    {}
func (*GreetManyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93e2bcf4a3ea62, []int{1}
}

func (m *GreetManyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyRequest.Unmarshal(m, b)
}
func (m *GreetManyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyRequest.Marshal(b, m, deterministic)
}
func (m *GreetManyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyRequest.Merge(m, src)
}
func (m *GreetManyRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyRequest.Size(m)
}
func (m *GreetManyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyRequest proto.InternalMessageInfo

func (m *GreetManyRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetManyResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyResponse) Reset()         { *m = GreetManyResponse{} }
func (m *GreetManyResponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyResponse) ProtoMessage()    {}
func (*GreetManyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93e2bcf4a3ea62, []int{2}
}

func (m *GreetManyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyResponse.Unmarshal(m, b)
}
func (m *GreetManyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyResponse.Marshal(b, m, deterministic)
}
func (m *GreetManyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyResponse.Merge(m, src)
}
func (m *GreetManyResponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyResponse.Size(m)
}
func (m *GreetManyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyResponse proto.InternalMessageInfo

func (m *GreetManyResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetManyRequest)(nil), "greet.GreetManyRequest")
	proto.RegisterType((*GreetManyResponse)(nil), "greet.GreetManyResponse")
}

func init() {
	proto.RegisterFile("02-ServerStreaming/proto/greet.proto", fileDescriptor_2c93e2bcf4a3ea62)
}

var fileDescriptor_2c93e2bcf4a3ea62 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x31, 0x30, 0xd2, 0x0d,
	0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x0a, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xcd, 0xcc, 0x4b, 0xd7, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2f, 0x4a, 0x4d, 0x2d, 0xd1, 0x03, 0xb3, 0x85, 0x58, 0xc1,
	0x1c, 0x25, 0x37, 0x2e, 0x0e, 0x77, 0x10, 0x23, 0x33, 0x2f, 0x5d, 0x48, 0x96, 0x8b, 0x2b, 0x2d,
	0xb3, 0xa8, 0xb8, 0x24, 0x3e, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88,
	0x13, 0x2c, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0x24, 0xcd, 0xc5, 0x99, 0x93, 0x08, 0x93, 0x65, 0x02,
	0xcb, 0x72, 0x80, 0x04, 0x40, 0x92, 0x4a, 0xf6, 0x5c, 0x02, 0x60, 0x73, 0x7c, 0x13, 0xf3, 0x2a,
	0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xb4, 0xb9, 0x38, 0xd2, 0xa1, 0x66, 0x83, 0x4d,
	0xe3, 0x36, 0xe2, 0xd7, 0x83, 0x38, 0x01, 0x66, 0x65, 0x10, 0x5c, 0x81, 0x92, 0x36, 0x97, 0x20,
	0x92, 0x01, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0x45, 0xa9, 0xc5, 0xa5,
	0x39, 0x25, 0x50, 0xd7, 0x40, 0x79, 0x46, 0xd1, 0x48, 0xb6, 0x81, 0xbc, 0x9a, 0x99, 0x9c, 0x2a,
	0xe4, 0xce, 0xc5, 0x07, 0x17, 0x0b, 0xc9, 0xcc, 0x4d, 0x2d, 0x16, 0x12, 0x47, 0xb6, 0x0d, 0xc9,
	0x61, 0x52, 0x12, 0x98, 0x12, 0x10, 0x0b, 0x95, 0x18, 0x0c, 0x18, 0x9d, 0x38, 0xa3, 0xd8, 0xc1,
	0xd2, 0x05, 0x49, 0x49, 0x6c, 0xe0, 0xb0, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x20, 0x10,
	0x24, 0x1c, 0x53, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetManyServiceClient is the client API for GreetManyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetManyServiceClient interface {
	GreetManyTimes(ctx context.Context, in *GreetManyRequest, opts ...grpc.CallOption) (GreetManyService_GreetManyTimesClient, error)
}

type greetManyServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetManyServiceClient(cc *grpc.ClientConn) GreetManyServiceClient {
	return &greetManyServiceClient{cc}
}

func (c *greetManyServiceClient) GreetManyTimes(ctx context.Context, in *GreetManyRequest, opts ...grpc.CallOption) (GreetManyService_GreetManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetManyService_serviceDesc.Streams[0], "/greet.GreetManyService/GreetManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetManyServiceGreetManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetManyService_GreetManyTimesClient interface {
	Recv() (*GreetManyResponse, error)
	grpc.ClientStream
}

type greetManyServiceGreetManyTimesClient struct {
	grpc.ClientStream
}

func (x *greetManyServiceGreetManyTimesClient) Recv() (*GreetManyResponse, error) {
	m := new(GreetManyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetManyServiceServer is the server API for GreetManyService service.
type GreetManyServiceServer interface {
	GreetManyTimes(*GreetManyRequest, GreetManyService_GreetManyTimesServer) error
}

// UnimplementedGreetManyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetManyServiceServer struct {
}

func (*UnimplementedGreetManyServiceServer) GreetManyTimes(req *GreetManyRequest, srv GreetManyService_GreetManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetManyTimes not implemented")
}

func RegisterGreetManyServiceServer(s *grpc.Server, srv GreetManyServiceServer) {
	s.RegisterService(&_GreetManyService_serviceDesc, srv)
}

func _GreetManyService_GreetManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetManyServiceServer).GreetManyTimes(m, &greetManyServiceGreetManyTimesServer{stream})
}

type GreetManyService_GreetManyTimesServer interface {
	Send(*GreetManyResponse) error
	grpc.ServerStream
}

type greetManyServiceGreetManyTimesServer struct {
	grpc.ServerStream
}

func (x *greetManyServiceGreetManyTimesServer) Send(m *GreetManyResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GreetManyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetManyService",
	HandlerType: (*GreetManyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetManyTimes",
			Handler:       _GreetManyService_GreetManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "02-ServerStreaming/proto/greet.proto",
}
